package com.example.localfind.ui

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

object LFS {
    private val en = mapOf(
        "find_me" to "Find Me",
        "controller" to "Controller",
        "app_name" to "Local Find",
        "how_to_use" to "How to Use",
        "how_step1" to "1. Tap Start Service.",
        "how_step2" to "2. Keep both devices on the same Wi-Fi or LAN.",
        "how_step3" to "3. On the controller, scan the QR code or enter the address shown here.",
        "how_step4" to "4. On the controller, tap Find Phone to ring or flash this phone.",
        "running" to "Running",
        "stopped" to "Stopped",
        "start_service" to "Start Service",
        "stop_service" to "Stop Service",
        "restart_http" to "Restart HTTP Server",
        "service_status" to "Service Status:",
        "last_error" to "Last Error:",
        "lan_address" to "LAN Address:",
        "port_label" to "Port:",
        "nsd" to "NSD:",
        "wake_lock" to "Wake Lock:",
        "wifi_lock" to "Wi-Fi Lock:",
        "service_type" to "Service Type:",
        "listening" to "Listening",
        "starting" to "Starting...",
        "failed" to "Failed",
        "idle" to "Idle",
        "advertising" to "Advertising",
        "advertised" to "Advertised",
        "held_cpu" to "Held (CPU)",
        "held_wifi" to "Held (Wi-Fi)",
        "not_held" to "Not held",
        "offline" to "Offline",
        "browser_remote" to "Remote Control in Browser:",
        "browser_hint" to "Open in a browser on the same Wi-Fi to control this phone.",
        "copy" to "Copy",
        "pairing_auth" to "Pairing & Authorization",
        "pairing_token" to "Pairing Token:",
        "show" to "Show",
        "hide" to "Hide",
        "reset_token" to "Reset Token",
        "na" to "N/A",
        "local_auth_failed_msg" to "Local auth failed",
        "partial_ring_flash_msg" to "Partial: ring started, flash failed",
        "stopped_msg" to "Stopped",
        "scanned_device" to "Scanned Device",
        "manual_device" to "Manual Device",
        "old_phone_placeholder" to "e.g. My old phone",
        "biometric_title" to "Local Identity Verification",
        "biometric_not_enrolled" to "Please set up a screen lock or biometric in system settings first.",
        "biometric_unavailable" to "Local authentication unavailable or not set up.",
        "generated_after_start" to "Generated after service start",
        "reset_token_title" to "Reset Token?",
        "reset_token_body" to "All paired controllers will be disconnected. They will need the new token to reconnect.",
        "reset" to "Reset",
        "cancel" to "Cancel",
        "controller_pairing" to "Controller Pairing Mode",
        "device_label" to "Device:",
        "device_id" to "Device ID:",
        "pairing_mode" to "Pairing Mode:",
        "enabled" to "Enabled",
        "disabled" to "Disabled",
        "remaining" to "Remaining:",
        "pairing_mode_hint" to "Pairing mode is active for a short window. Requests must be confirmed on this phone.",
        "renew_5min" to "Renew 5 min",
        "enable_pairing" to "Enable Pairing",
        "disable_pairing" to "Disable Pairing",
        "pending_requests" to "Pending Requests",
        "type_label" to "Type:",
        "accept" to "Accept",
        "reject" to "Reject",
        "no_pending" to "No pending requests.",
        "pairing_qr" to "Pairing QR Code",
        "qr_hint1" to "Scan from controller to pair",
        "qr_hint2" to "QR code is LAN-only",
        "qr_hint3" to "Reset token if compromised",
        "security" to "Security & Privacy",
        "sec1" to "Tokens are LAN-only. Nothing is uploaded to the cloud.",
        "sec2" to "Do not share tokens with untrusted parties.",
        "sec3" to "Reset the token if you suspect it has leaked.",
        "background" to "Background Running",
        "bg1" to "The service runs as a foreground service. Some devices (Xiaomi, Huawei, Oppo) may restrict background network after screen lock.",
        "bg2" to "Set this app to \"Don't optimize\" or \"Allow background activity\" in system settings.",
        "bg3" to "Some devices disable Wi-Fi on screen lock. Enable \"Keep Wi-Fi on during sleep\" in system settings.",
        "battery_settings" to "Battery Optimization Settings",
        "device_test" to "Device Test",
        "ring_label" to "Ring",
        "flash_label" to "Flash",
        "silent" to "Silent",
        "ringing" to "Ringing",
        "steady" to "Steady",
        "strobe" to "Strobe",
        "off" to "Off",
        "test_ring" to "Test Ring",
        "stop_ring" to "Stop Ring",
        "test_flash" to "Test Flash",
        "test_strobe" to "Test Strobe",
        "turn_flash_off" to "Turn Flash Off",
        "stop_all_alerts" to "Stop All Alerts",
        "saved_devices" to "Saved Devices",
        "recent" to "Recent",
        "connect" to "Connect",
        "delete" to "Delete",
        "device_discovery" to "Device Discovery (NSD)",
        "status_label" to "Status:",
        "scanning" to "Scanning...",
        "scan_failed" to "Scan Failed",
        "scan" to "Scan",
        "stop" to "Stop",
        "scan_qr_connect" to "Scan QR Code to Connect",
        "no_other_devices" to "No other devices found",
        "discovery_hint" to "Make sure both phones are on the same Wi-Fi. This device is hidden from the list. Try Manual Connection below if discovery fails.",
        "manual_connection" to "Manual Connection",
        "manual_hint" to "Enter the target phone IP address. Default port is 8888.",
        "ip_address" to "IP Address",
        "port" to "Port",
        "custom_name_opt" to "Custom Name (optional)",
        "open_in_app" to "Open in App",
        "open_in_browser" to "Open in Browser",
        "back" to "Back",
        "online" to "Online",
        "offline_svc" to "Offline / Service down",
        "timeout" to "Timeout",
        "token_error" to "Token error",
        "connecting" to "Connecting...",
        "searching" to "Searching",
        "partial_ringing" to "Partial (ringing)",
        "find_phone" to "Find Phone",
        "stop_label" to "Stop",
        "remote_ring" to "Ring",
        "remote_flash" to "Flash",
        "authorization" to "Authorization",
        "token_saved" to "Token saved",
        "clear" to "Clear",
        "new_token_opt" to "New token (optional)",
        "enter_token_target" to "Enter token from target phone",
        "hardware_ctrl" to "Hardware Controls",
        "refresh" to "Refresh",
        "alarm_loud" to "Alarm (loud)",
        "not_valid_code" to "Not a valid Local Find pairing code",
        "qr_parse_failed" to "QR parse failed",
        "enter_ip" to "Enter IP Address",
        "invalid_port" to "Invalid port (1-65535)",
        "verify_send" to "Verify to send command",
        "verify_find" to "Verify to find phone",
        "verify_stop" to "Verify to stop",
        "command_sent" to "Command sent",
        "device_offline" to "Device offline or service down",
        "command_failed" to "Command failed",
        "local_auth_failed" to "Local auth failed",
        "partial_ring_flash" to "Partial: ring started, flash failed",
        "enter_token_first" to "Enter token first",
        "align_qr" to "Align QR code inside the frame",
        "close" to "Close",
        "current_device" to "Current Device",
        "name" to "Name",
        "address" to "Address",
        "mode" to "Mode",
        "manual_mode" to "Manual",
        "not_saved" to "Not Saved",
        "last_connected" to "Last success: ",
        "not_connected" to "Not Connected",
        "check_connection" to "Check Connection",
        "send_pairing_request" to "Send Pairing Request",
        "not_checked" to "Not Checked",
        "access_protection" to "Access Protection",
        "protection_method" to "Protection Method",
        "registered" to "Registered",
        "not_registered" to "Not registered",
        "webauthn_label" to "WebAuthn",
        "pin_label" to "Local PIN",
        "webauthn_fb_pin" to "WebAuthn, with PIN fallback",
        "register_webauthn" to "Register WebAuthn",
        "test_webauthn" to "Test WebAuthn",
    )

    private val zh = mapOf(
        "find_me" to "找到我",
        "controller" to "控制端",
        "app_name" to "Local Find",
        "how_to_use" to "使用说明",
        "how_step1" to "1. 点击启动服务。",
        "how_step2" to "2. 保持两台设备在同一 Wi-Fi 或局域网。",
        "how_step3" to "3. 在控制端扫描二维码或输入此处显示的地址。",
        "how_step4" to "4. 在控制端点击查找手机以响铃或闪光。",
        "running" to "运行中",
        "stopped" to "已停止",
        "start_service" to "启动服务",
        "stop_service" to "停止服务",
        "restart_http" to "重启 HTTP 服务",
        "service_status" to "服务状态：",
        "last_error" to "最近错误：",
        "lan_address" to "局域网地址：",
        "port_label" to "端口：",
        "nsd" to "NSD：",
        "wake_lock" to "唤醒锁：",
        "wifi_lock" to "Wi-Fi 锁：",
        "service_type" to "服务类型：",
        "listening" to "监听中",
        "starting" to "启动中...",
        "failed" to "失败",
        "idle" to "空闲",
        "advertising" to "广播中",
        "advertised" to "已广播",
        "held_cpu" to "已保持（CPU）",
        "held_wifi" to "已保持（Wi-Fi）",
        "not_held" to "未保持",
        "offline" to "未连接",
        "browser_remote" to "浏览器远程控制：",
        "browser_hint" to "在同一 Wi-Fi 的浏览器中打开此地址即可控制本手机。",
        "copy" to "复制",
        "pairing_auth" to "配对与授权",
        "pairing_token" to "配对令牌：",
        "show" to "显示",
        "hide" to "隐藏",
        "reset_token" to "重置令牌",
        "na" to "无",
        "local_auth_failed_msg" to "本机认证失败",
        "partial_ring_flash_msg" to "部分成功：响铃已启动，闪光失败",
        "stopped_msg" to "已停止",
        "scanned_device" to "已扫描设备",
        "manual_device" to "手动设备",
        "old_phone_placeholder" to "例如：我的旧手机",
        "biometric_title" to "本地身份认证",
        "biometric_not_enrolled" to "请先在本机系统中设置锁屏密码或生物识别",
        "biometric_unavailable" to "本机认证不可用或未设置锁屏",
        "generated_after_start" to "服务启动后生成",
        "reset_token_title" to "重置令牌？",
        "reset_token_body" to "所有已配对的控制器将断开连接，需要使用新令牌重新连接。",
        "reset" to "重置",
        "cancel" to "取消",
        "controller_pairing" to "控制器配对模式",
        "device_label" to "设备：",
        "device_id" to "设备 ID：",
        "pairing_mode" to "配对模式：",
        "enabled" to "已开启",
        "disabled" to "已关闭",
        "remaining" to "剩余时间：",
        "pairing_mode_hint" to "配对模式仅在短时间内有效。配对请求必须在本手机上确认。",
        "renew_5min" to "续期 5 分钟",
        "enable_pairing" to "开启配对",
        "disable_pairing" to "关闭配对",
        "pending_requests" to "待处理请求",
        "type_label" to "类型：",
        "accept" to "接受",
        "reject" to "拒绝",
        "no_pending" to "没有待处理请求。",
        "pairing_qr" to "配对二维码",
        "qr_hint1" to "控制端扫码即可快速连接",
        "qr_hint2" to "二维码仅限局域网使用",
        "qr_hint3" to "如泄露请重置令牌",
        "security" to "安全与隐私",
        "sec1" to "令牌仅限局域网使用，不会上传云端。",
        "sec2" to "请勿将令牌提供给不可信的人。",
        "sec3" to "如怀疑令牌泄露，请重置令牌。",
        "background" to "后台运行",
        "bg1" to "服务以前台模式运行。部分设备（小米、华为、OPPO）锁屏后可能限制后台网络。",
        "bg2" to "请在系统设置中将本应用设为「不优化电池」或「允许后台活动」。",
        "bg3" to "部分设备锁屏后会断开 Wi-Fi，请在系统设置中开启「锁屏后保持 Wi-Fi 连接」。",
        "battery_settings" to "电池优化设置",
        "device_test" to "设备测试",
        "ring_label" to "响铃",
        "flash_label" to "闪光",
        "silent" to "静音",
        "ringing" to "响铃中",
        "steady" to "常亮",
        "strobe" to "闪烁",
        "off" to "关闭",
        "test_ring" to "测试响铃",
        "stop_ring" to "停止响铃",
        "test_flash" to "测试闪光",
        "test_strobe" to "测试闪烁",
        "turn_flash_off" to "关闭闪光",
        "stop_all_alerts" to "停止所有警报",
        "saved_devices" to "已保存设备",
        "recent" to "最近",
        "connect" to "连接",
        "delete" to "删除",
        "device_discovery" to "设备发现（NSD）",
        "status_label" to "状态：",
        "scanning" to "扫描中...",
        "scan_failed" to "扫描失败",
        "scan" to "扫描",
        "stop" to "停止",
        "scan_qr_connect" to "扫描二维码连接",
        "no_other_devices" to "未发现其他设备",
        "discovery_hint" to "请确认两台手机在同一 Wi-Fi。本机不会出现在列表中。如仍无法发现，请尝试下方的手动连接。",
        "manual_connection" to "手动连接",
        "manual_hint" to "输入目标手机 IP 地址，默认端口 8888。",
        "ip_address" to "IP 地址",
        "port" to "端口",
        "custom_name_opt" to "自定义名称（可选）",
        "open_in_app" to "在 App 中打开",
        "open_in_browser" to "在浏览器中打开",
        "back" to "返回",
        "online" to "在线",
        "offline_svc" to "离线 / 服务未启动",
        "timeout" to "超时",
        "token_error" to "令牌错误",
        "connecting" to "连接中...",
        "searching" to "查找中",
        "partial_ringing" to "部分（响铃中）",
        "find_phone" to "查找手机",
        "stop_label" to "停止",
        "remote_ring" to "响铃",
        "remote_flash" to "闪光",
        "authorization" to "授权",
        "token_saved" to "令牌已保存",
        "clear" to "清除",
        "new_token_opt" to "新令牌（可选）",
        "enter_token_target" to "请输入目标手机显示的令牌",
        "hardware_ctrl" to "硬件控制",
        "refresh" to "刷新",
        "alarm_loud" to "报警（会响）",
        "not_valid_code" to "不是有效的 Local Find 配对码",
        "qr_parse_failed" to "二维码解析失败",
        "enter_ip" to "请输入 IP 地址",
        "invalid_port" to "端口无效 (1-65535)",
        "verify_send" to "验证身份以发送命令",
        "verify_find" to "验证身份以查找手机",
        "verify_stop" to "验证身份以停止",
        "command_sent" to "命令已发送",
        "device_offline" to "设备离线或服务未启动",
        "command_failed" to "命令失败",
        "local_auth_failed" to "本机认证失败",
        "partial_ring_flash" to "部分成功：响铃已启动，闪光失败",
        "enter_token_first" to "请先输入令牌",
        "align_qr" to "将二维码放入框内",
        "close" to "关闭",
        "current_device" to "当前设备",
        "name" to "名称",
        "address" to "地址",
        "mode" to "模式",
        "manual_mode" to "手动模式",
        "not_saved" to "未保存",
        "last_connected" to "上次连接：",
        "not_connected" to "未连接",
        "check_connection" to "检查连接",
        "send_pairing_request" to "发送配对请求",
        "not_checked" to "未检查",
        "access_protection" to "访问保护",
        "protection_method" to "保护方式",
        "registered" to "已注册",
        "not_registered" to "未注册",
        "webauthn_label" to "WebAuthn",
        "pin_label" to "本地 PIN",
        "webauthn_fb_pin" to "WebAuthn，PIN 备用",
        "register_webauthn" to "注册 WebAuthn",
        "test_webauthn" to "测试 WebAuthn",
    )

    private var lang by mutableStateOf("en")

    fun setLanguage(l: String) { lang = l }
    fun getLanguage(): String = lang

    fun str(key: String): String {
        val currentLang = lang
        val dict = if (currentLang == "zh") zh else en
        return dict[key] ?: en[key] ?: key
    }
}
